"""empty message

Revision ID: 95586557b4b1
Revises: f05565bd66ce
Create Date: 2023-05-13 09:12:23.064250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95586557b4b1'
down_revision = 'f05565bd66ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
