"""empty message

Revision ID: dad6357b24a1
Revises: b9bb3d6357a2
Create Date: 2023-05-13 10:18:27.478783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dad6357b24a1'
down_revision = 'b9bb3d6357a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['company_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
